dist: bionic
language: python # 默认是ruby
python: 3.7
strategy: git
root: linux
install:
  # nuo主题需要extended版本的hugo，其他主题可以用最新的普通版本就行
  - wget https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_0.79.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.debå

# before_script:
#   - rm -rf ./public
#   - git submodule init
#   - git submodule update

script:
  - hugo

# after_script:
#   - cd ./public
#   - git add .
#   - git commit -m "feat:update by travis ci"
#   - git push origin HEAD:master

# 构建完成后会自动更新Github Pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  repo: aresprotocolnz.github.io
  target_branch: master
  email: aresprotocolnz@gmail.com
  name: aresprotocolnz
